
import { CommonBase, UInt5, WitnessVersion, UnqualifiedError } from './CommonBase.mjs';
import * as bindings from '../bindings.mjs'


/**
 * One counterparty's public keys which do not change over the life of a channel.
 */
export class ChannelPublicKeys extends CommonBase {
	/* @internal */
	public constructor(_dummy: null, ptr: bigint) {
		super(ptr, bindings.ChannelPublicKeys_free);
	}

	/**
	 * The public key which is used to sign all commitment transactions, as it appears in the
	 * on-chain channel lock-in 2-of-2 multisig output.
	 */
	public get_funding_pubkey(): Uint8Array {
		const ret: number = bindings.ChannelPublicKeys_get_funding_pubkey(this.ptr);
		const ret_conv: Uint8Array = bindings.decodeUint8Array(ret);
		return ret_conv;
	}

	/**
	 * The public key which is used to sign all commitment transactions, as it appears in the
	 * on-chain channel lock-in 2-of-2 multisig output.
	 */
	public set_funding_pubkey(val: Uint8Array): void {
		bindings.ChannelPublicKeys_set_funding_pubkey(this.ptr, bindings.encodeUint8Array(val));
	}

	/**
	 * The base point which is used (with [`RevocationKey::from_basepoint`]) to derive per-commitment
	 * revocation keys. This is combined with the per-commitment-secret generated by the
	 * counterparty to create a secret which the counterparty can reveal to revoke previous
	 * states.
	 */
	public get_revocation_basepoint(): RevocationBasepoint {
		const ret: bigint = bindings.ChannelPublicKeys_get_revocation_basepoint(this.ptr);
		const ret_hu_conv: RevocationBasepoint = new RevocationBasepoint(null, ret);
		CommonBase.add_ref_from(ret_hu_conv, this);
		return ret_hu_conv;
	}

	/**
	 * The base point which is used (with [`RevocationKey::from_basepoint`]) to derive per-commitment
	 * revocation keys. This is combined with the per-commitment-secret generated by the
	 * counterparty to create a secret which the counterparty can reveal to revoke previous
	 * states.
	 */
	public set_revocation_basepoint(val: RevocationBasepoint): void {
		bindings.ChannelPublicKeys_set_revocation_basepoint(this.ptr, CommonBase.get_ptr_of(val));
	}

	/**
	 * The public key on which the non-broadcaster (ie the countersignatory) receives an immediately
	 * spendable primary channel balance on the broadcaster's commitment transaction. This key is
	 * static across every commitment transaction.
	 */
	public get_payment_point(): Uint8Array {
		const ret: number = bindings.ChannelPublicKeys_get_payment_point(this.ptr);
		const ret_conv: Uint8Array = bindings.decodeUint8Array(ret);
		return ret_conv;
	}

	/**
	 * The public key on which the non-broadcaster (ie the countersignatory) receives an immediately
	 * spendable primary channel balance on the broadcaster's commitment transaction. This key is
	 * static across every commitment transaction.
	 */
	public set_payment_point(val: Uint8Array): void {
		bindings.ChannelPublicKeys_set_payment_point(this.ptr, bindings.encodeUint8Array(val));
	}

	/**
	 * The base point which is used (with derive_public_key) to derive a per-commitment payment
	 * public key which receives non-HTLC-encumbered funds which are only available for spending
	 * after some delay (or can be claimed via the revocation path).
	 */
	public get_delayed_payment_basepoint(): DelayedPaymentBasepoint {
		const ret: bigint = bindings.ChannelPublicKeys_get_delayed_payment_basepoint(this.ptr);
		const ret_hu_conv: DelayedPaymentBasepoint = new DelayedPaymentBasepoint(null, ret);
		CommonBase.add_ref_from(ret_hu_conv, this);
		return ret_hu_conv;
	}

	/**
	 * The base point which is used (with derive_public_key) to derive a per-commitment payment
	 * public key which receives non-HTLC-encumbered funds which are only available for spending
	 * after some delay (or can be claimed via the revocation path).
	 */
	public set_delayed_payment_basepoint(val: DelayedPaymentBasepoint): void {
		bindings.ChannelPublicKeys_set_delayed_payment_basepoint(this.ptr, CommonBase.get_ptr_of(val));
	}

	/**
	 * The base point which is used (with derive_public_key) to derive a per-commitment public key
	 * which is used to encumber HTLC-in-flight outputs.
	 */
	public get_htlc_basepoint(): HtlcBasepoint {
		const ret: bigint = bindings.ChannelPublicKeys_get_htlc_basepoint(this.ptr);
		const ret_hu_conv: HtlcBasepoint = new HtlcBasepoint(null, ret);
		CommonBase.add_ref_from(ret_hu_conv, this);
		return ret_hu_conv;
	}

	/**
	 * The base point which is used (with derive_public_key) to derive a per-commitment public key
	 * which is used to encumber HTLC-in-flight outputs.
	 */
	public set_htlc_basepoint(val: HtlcBasepoint): void {
		bindings.ChannelPublicKeys_set_htlc_basepoint(this.ptr, CommonBase.get_ptr_of(val));
	}

	/**
	 * Constructs a new ChannelPublicKeys given each field
	 */
	public static constructor_new(funding_pubkey_arg: Uint8Array, revocation_basepoint_arg: RevocationBasepoint, payment_point_arg: Uint8Array, delayed_payment_basepoint_arg: DelayedPaymentBasepoint, htlc_basepoint_arg: HtlcBasepoint): ChannelPublicKeys {
		const ret: bigint = bindings.ChannelPublicKeys_new(bindings.encodeUint8Array(funding_pubkey_arg), CommonBase.get_ptr_of(revocation_basepoint_arg), bindings.encodeUint8Array(payment_point_arg), CommonBase.get_ptr_of(delayed_payment_basepoint_arg), CommonBase.get_ptr_of(htlc_basepoint_arg));
		const ret_hu_conv: ChannelPublicKeys = new ChannelPublicKeys(null, ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	public clone_ptr(): bigint {
		const ret: bigint = bindings.ChannelPublicKeys_clone_ptr(this.ptr);
		return ret;
	}

	/**
	 * Creates a copy of the ChannelPublicKeys
	 */
	public clone(): ChannelPublicKeys {
		const ret: bigint = bindings.ChannelPublicKeys_clone(this.ptr);
		const ret_hu_conv: ChannelPublicKeys = new ChannelPublicKeys(null, ret);
		CommonBase.add_ref_from(ret_hu_conv, this);
		return ret_hu_conv;
	}

	/**
	 * Generates a non-cryptographic 64-bit hash of the ChannelPublicKeys.
	 */
	public hash(): bigint {
		const ret: bigint = bindings.ChannelPublicKeys_hash(this.ptr);
		return ret;
	}

	/**
	 * Checks if two ChannelPublicKeyss contain equal inner contents.
	 * This ignores pointers and is_owned flags and looks at the values in fields.
	 * Two objects with NULL inner values will be considered "equal" here.
	 */
	public eq(b: ChannelPublicKeys): boolean {
		const ret: boolean = bindings.ChannelPublicKeys_eq(this.ptr, CommonBase.get_ptr_of(b));
		return ret;
	}

	/**
	 * Serialize the ChannelPublicKeys object into a byte array which can be read by ChannelPublicKeys_read
	 */
	public write(): Uint8Array {
		const ret: number = bindings.ChannelPublicKeys_write(this.ptr);
		const ret_conv: Uint8Array = bindings.decodeUint8Array(ret);
		return ret_conv;
	}

	/**
	 * Read a ChannelPublicKeys from a byte array, created by ChannelPublicKeys_write
	 */
	public static constructor_read(ser: Uint8Array): Result_ChannelPublicKeysDecodeErrorZ {
		const ret: bigint = bindings.ChannelPublicKeys_read(bindings.encodeUint8Array(ser));
		const ret_hu_conv: Result_ChannelPublicKeysDecodeErrorZ = Result_ChannelPublicKeysDecodeErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

}
