
import { CommonBase, UInt5, WitnessVersion, UnqualifiedError } from './CommonBase.mjs';
import * as bindings from '../bindings.mjs'


/**
 * An update generated by the underlying channel itself which contains some new information the
 * [`ChannelMonitor`] should be made aware of.
 * 
 * Because this represents only a small number of updates to the underlying state, it is generally
 * much smaller than a full [`ChannelMonitor`]. However, for large single commitment transaction
 * updates (e.g. ones during which there are hundreds of HTLCs pending on the commitment
 * transaction), a single update may reach upwards of 1 MiB in serialized size.
 */
export class ChannelMonitorUpdate extends CommonBase {
	/* @internal */
	public constructor(_dummy: null, ptr: bigint) {
		super(ptr, bindings.ChannelMonitorUpdate_free);
	}

	/**
	 * The sequence number of this update. Updates *must* be replayed in-order according to this
	 * sequence number (and updates may panic if they are not). The update_id values are strictly
	 * increasing and increase by one for each new update, with two exceptions specified below.
	 * 
	 * This sequence number is also used to track up to which points updates which returned
	 * [`ChannelMonitorUpdateStatus::InProgress`] have been applied to all copies of a given
	 * ChannelMonitor when ChannelManager::channel_monitor_updated is called.
	 * 
	 * Note that for [`ChannelMonitorUpdate`]s generated on LDK versions prior to 0.1 after the
	 * channel was closed, this value may be [`u64::MAX`]. In that case, multiple updates may
	 * appear with the same ID, and all should be replayed.
	 * 
	 * [`ChannelMonitorUpdateStatus::InProgress`]: super::ChannelMonitorUpdateStatus::InProgress
	 */
	public get_update_id(): bigint {
		const ret: bigint = bindings.ChannelMonitorUpdate_get_update_id(this.ptr);
		return ret;
	}

	/**
	 * The sequence number of this update. Updates *must* be replayed in-order according to this
	 * sequence number (and updates may panic if they are not). The update_id values are strictly
	 * increasing and increase by one for each new update, with two exceptions specified below.
	 * 
	 * This sequence number is also used to track up to which points updates which returned
	 * [`ChannelMonitorUpdateStatus::InProgress`] have been applied to all copies of a given
	 * ChannelMonitor when ChannelManager::channel_monitor_updated is called.
	 * 
	 * Note that for [`ChannelMonitorUpdate`]s generated on LDK versions prior to 0.1 after the
	 * channel was closed, this value may be [`u64::MAX`]. In that case, multiple updates may
	 * appear with the same ID, and all should be replayed.
	 * 
	 * [`ChannelMonitorUpdateStatus::InProgress`]: super::ChannelMonitorUpdateStatus::InProgress
	 */
	public set_update_id(val: bigint): void {
		bindings.ChannelMonitorUpdate_set_update_id(this.ptr, val);
	}

	/**
	 * The channel ID associated with these updates.
	 * 
	 * Will be `None` for `ChannelMonitorUpdate`s constructed on LDK versions prior to 0.0.121 and
	 * always `Some` otherwise.
	 * 
	 * Note that the return value (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	public get_channel_id(): ChannelId {
		const ret: bigint = bindings.ChannelMonitorUpdate_get_channel_id(this.ptr);
		const ret_hu_conv: ChannelId = new ChannelId(null, ret);
		CommonBase.add_ref_from(ret_hu_conv, this);
		return ret_hu_conv;
	}

	/**
	 * The channel ID associated with these updates.
	 * 
	 * Will be `None` for `ChannelMonitorUpdate`s constructed on LDK versions prior to 0.0.121 and
	 * always `Some` otherwise.
	 * 
	 * Note that val (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	public set_channel_id(val: ChannelId|null): void {
		bindings.ChannelMonitorUpdate_set_channel_id(this.ptr, val == null ? 0n : CommonBase.get_ptr_of(val));
	}

	public clone_ptr(): bigint {
		const ret: bigint = bindings.ChannelMonitorUpdate_clone_ptr(this.ptr);
		return ret;
	}

	/**
	 * Creates a copy of the ChannelMonitorUpdate
	 */
	public clone(): ChannelMonitorUpdate {
		const ret: bigint = bindings.ChannelMonitorUpdate_clone(this.ptr);
		const ret_hu_conv: ChannelMonitorUpdate = new ChannelMonitorUpdate(null, ret);
		CommonBase.add_ref_from(ret_hu_conv, this);
		return ret_hu_conv;
	}

	/**
	 * Checks if two ChannelMonitorUpdates contain equal inner contents.
	 * This ignores pointers and is_owned flags and looks at the values in fields.
	 * Two objects with NULL inner values will be considered "equal" here.
	 */
	public eq(b: ChannelMonitorUpdate): boolean {
		const ret: boolean = bindings.ChannelMonitorUpdate_eq(this.ptr, CommonBase.get_ptr_of(b));
		return ret;
	}

	/**
	 * Returns a `Vec` of new (funding outpoint, funding script) to monitor the chain for as a
	 * result of a renegotiated funding transaction.
	 */
	public renegotiated_funding_data(): TwoTuple_OutPointCVec_u8ZZ[] {
		const ret: number = bindings.ChannelMonitorUpdate_renegotiated_funding_data(this.ptr);
		const ret_conv_28_len: number = bindings.getArrayLength(ret);
		const ret_conv_28_arr: TwoTuple_OutPointCVec_u8ZZ[] = new Array(ret_conv_28_len).fill(null);
		for (var c = 0; c < ret_conv_28_len; c++) {
			const ret_conv_28: bigint = bindings.getU64ArrayElem(ret, c);
			const ret_conv_28_hu_conv: TwoTuple_OutPointCVec_u8ZZ = new TwoTuple_OutPointCVec_u8ZZ(null, ret_conv_28);
			CommonBase.add_ref_from(ret_conv_28_hu_conv, this);
			ret_conv_28_arr[c] = ret_conv_28_hu_conv;
		}
		bindings.freeWasmMemory(ret)
		return ret_conv_28_arr;
	}

	/**
	 * Serialize the ChannelMonitorUpdate object into a byte array which can be read by ChannelMonitorUpdate_read
	 */
	public write(): Uint8Array {
		const ret: number = bindings.ChannelMonitorUpdate_write(this.ptr);
		const ret_conv: Uint8Array = bindings.decodeUint8Array(ret);
		return ret_conv;
	}

	/**
	 * Read a ChannelMonitorUpdate from a byte array, created by ChannelMonitorUpdate_write
	 */
	public static constructor_read(ser: Uint8Array): Result_ChannelMonitorUpdateDecodeErrorZ {
		const ret: bigint = bindings.ChannelMonitorUpdate_read(bindings.encodeUint8Array(ser));
		const ret_hu_conv: Result_ChannelMonitorUpdateDecodeErrorZ = Result_ChannelMonitorUpdateDecodeErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

}
