

import { CommonBase, UInt5, WitnessVersion, UnqualifiedError } from './CommonBase.mjs';
import * as bindings from '../bindings.mjs'



/** An implementation of CustomMessageHandler */
export interface CustomMessageHandlerInterface {
	/**Handles the given message sent from `sender_node_id`, possibly producing messages for
	 * [`CustomMessageHandler::get_and_clear_pending_msg`] to return and thus for [`PeerManager`]
	 * to send.
	 */
	handle_custom_message(msg: Type, sender_node_id: Uint8Array): Result_NoneLightningErrorZ;
	/**Returns the list of pending messages that were generated by the handler, clearing the list
	 * in the process. Each message is paired with the node id of the intended recipient. If no
	 * connection to the node exists, then the message is simply not sent.
	 */
	get_and_clear_pending_msg(): TwoTuple_PublicKeyTypeZ[];
	/**Indicates a peer disconnected.
	 */
	peer_disconnected(their_node_id: Uint8Array): void;
	/**Handle a peer connecting.
	 * 
	 * May return an `Err(())` to indicate that we should immediately disconnect from the peer
	 * (e.g. because the features they support are not sufficient to communicate with us).
	 * 
	 * Note, of course, that other message handlers may wish to communicate with the peer, which
	 * disconnecting them will prevent.
	 * 
	 * [`Self::peer_disconnected`] will not be called if `Err(())` is returned.
	 */
	peer_connected(their_node_id: Uint8Array, msg: Init, inbound: boolean): Result_NoneNoneZ;
	/**Gets the node feature flags which this handler itself supports. All available handlers are
	 * queried similarly and their feature flags are OR'd together to form the [`NodeFeatures`]
	 * which are broadcasted in our [`NodeAnnouncement`] message.
	 * 
	 * [`NodeAnnouncement`]: crate::ln::msgs::NodeAnnouncement
	 */
	provided_node_features(): NodeFeatures;
	/**Gets the init feature flags which should be sent to the given peer. All available handlers
	 * are queried similarly and their feature flags are OR'd together to form the [`InitFeatures`]
	 * which are sent in our [`Init`] message.
	 * 
	 * [`Init`]: crate::ln::msgs::Init
	 */
	provided_init_features(their_node_id: Uint8Array): InitFeatures;
}

class LDKCustomMessageHandlerHolder {
	held: CustomMessageHandler|null = null;
}

/**
 * A handler provided to [`PeerManager`] for reading and handling custom messages.
 * 
 * [BOLT 1] specifies a custom message type range for use with experimental or application-specific
 * messages. `CustomMessageHandler` allows for user-defined handling of such types. See the
 * [`lightning_custom_message`] crate for tools useful in composing more than one custom handler.
 * 
 * [BOLT 1]: https://github.com/lightning/bolts/blob/master/01-messaging.md
 * [`lightning_custom_message`]: https://docs.rs/lightning_custom_message/latest/lightning_custom_message
 */
export class CustomMessageHandler extends CommonBase {
	/* @internal */
	public bindings_instance: bindings.LDKCustomMessageHandler|null;

	/* @internal */
	public instance_idx?: number;

	/* @internal */
	constructor(_dummy: null, ptr: bigint) {
		super(ptr, bindings.CustomMessageHandler_free);
		this.bindings_instance = null;
	}

	/** Creates a new instance of CustomMessageHandler from a given implementation */
	public static new_impl(arg: CustomMessageHandlerInterface, customMessageReader_impl: CustomMessageReaderInterface): CustomMessageHandler {
		const impl_holder: LDKCustomMessageHandlerHolder = new LDKCustomMessageHandlerHolder();
		let structImplementation = {
			handle_custom_message (msg: bigint, sender_node_id: number): bigint {
				const ret_hu_conv: Type = new Type(null, msg);
				CommonBase.add_ref_from(ret_hu_conv, this);
				const sender_node_id_conv: Uint8Array = bindings.decodeUint8Array(sender_node_id);
				const ret: Result_NoneLightningErrorZ = arg.handle_custom_message(ret_hu_conv, sender_node_id_conv);
				const result: bigint = ret.clone_ptr();
				return result;
			},
			get_and_clear_pending_msg (): number {
				const ret: TwoTuple_PublicKeyTypeZ[] = arg.get_and_clear_pending_msg();
				const result: number = bindings.encodeUint64Array(ret.map(ret_conv_25 => ret_conv_25.clone_ptr()));
				return result;
			},
			peer_disconnected (their_node_id: number): void {
				const their_node_id_conv: Uint8Array = bindings.decodeUint8Array(their_node_id);
				arg.peer_disconnected(their_node_id_conv);
			},
			peer_connected (their_node_id: number, msg: bigint, inbound: boolean): bigint {
				const their_node_id_conv: Uint8Array = bindings.decodeUint8Array(their_node_id);
				const msg_hu_conv: Init = new Init(null, msg);
				const ret: Result_NoneNoneZ = arg.peer_connected(their_node_id_conv, msg_hu_conv, inbound);
				const result: bigint = ret.clone_ptr();
				return result;
			},
			provided_node_features (): bigint {
				const ret: NodeFeatures = arg.provided_node_features();
				const result: bigint = ret.clone_ptr();
				return result;
			},
			provided_init_features (their_node_id: number): bigint {
				const their_node_id_conv: Uint8Array = bindings.decodeUint8Array(their_node_id);
				const ret: InitFeatures = arg.provided_init_features(their_node_id_conv);
				const result: bigint = ret.clone_ptr();
				return result;
			},
		} as bindings.LDKCustomMessageHandler;
		const customMessageReader = CustomMessageReader.new_impl(customMessageReader_impl);
		const ptr_idx: [bigint, number] = bindings.LDKCustomMessageHandler_new(structImplementation, customMessageReader.instance_idx!);

		impl_holder.held = new CustomMessageHandler(null, ptr_idx[0]);
		impl_holder.held.instance_idx = ptr_idx[1];
		impl_holder.held.bindings_instance = structImplementation;
		impl_holder.held.ptrs_to.push(customMessageReader);
		return impl_holder.held!;
	}

	/**
	 * Handles the given message sent from `sender_node_id`, possibly producing messages for
	 * [`CustomMessageHandler::get_and_clear_pending_msg`] to return and thus for [`PeerManager`]
	 * to send.
	 */
	public handle_custom_message(msg: Type, sender_node_id: Uint8Array): Result_NoneLightningErrorZ {
		const ret: bigint = bindings.CustomMessageHandler_handle_custom_message(this.ptr, CommonBase.get_ptr_of(msg), bindings.encodeUint8Array(sender_node_id));
		const ret_hu_conv: Result_NoneLightningErrorZ = Result_NoneLightningErrorZ.constr_from_ptr(ret);
		CommonBase.add_ref_from(this, msg);
		return ret_hu_conv;
	}

	/**
	 * Returns the list of pending messages that were generated by the handler, clearing the list
	 * in the process. Each message is paired with the node id of the intended recipient. If no
	 * connection to the node exists, then the message is simply not sent.
	 */
	public get_and_clear_pending_msg(): TwoTuple_PublicKeyTypeZ[] {
		const ret: number = bindings.CustomMessageHandler_get_and_clear_pending_msg(this.ptr);
		const ret_conv_25_len: number = bindings.getArrayLength(ret);
		const ret_conv_25_arr: TwoTuple_PublicKeyTypeZ[] = new Array(ret_conv_25_len).fill(null);
		for (var z = 0; z < ret_conv_25_len; z++) {
			const ret_conv_25: bigint = bindings.getU64ArrayElem(ret, z);
			const ret_conv_25_hu_conv: TwoTuple_PublicKeyTypeZ = new TwoTuple_PublicKeyTypeZ(null, ret_conv_25);
			CommonBase.add_ref_from(ret_conv_25_hu_conv, this);
			ret_conv_25_arr[z] = ret_conv_25_hu_conv;
		}
		bindings.freeWasmMemory(ret)
		return ret_conv_25_arr;
	}

	/**
	 * Indicates a peer disconnected.
	 */
	public peer_disconnected(their_node_id: Uint8Array): void {
		bindings.CustomMessageHandler_peer_disconnected(this.ptr, bindings.encodeUint8Array(their_node_id));
	}

	/**
	 * Handle a peer connecting.
	 * 
	 * May return an `Err(())` to indicate that we should immediately disconnect from the peer
	 * (e.g. because the features they support are not sufficient to communicate with us).
	 * 
	 * Note, of course, that other message handlers may wish to communicate with the peer, which
	 * disconnecting them will prevent.
	 * 
	 * [`Self::peer_disconnected`] will not be called if `Err(())` is returned.
	 */
	public peer_connected(their_node_id: Uint8Array, msg: Init, inbound: boolean): Result_NoneNoneZ {
		const ret: bigint = bindings.CustomMessageHandler_peer_connected(this.ptr, bindings.encodeUint8Array(their_node_id), CommonBase.get_ptr_of(msg), inbound);
		const ret_hu_conv: Result_NoneNoneZ = Result_NoneNoneZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Gets the node feature flags which this handler itself supports. All available handlers are
	 * queried similarly and their feature flags are OR'd together to form the [`NodeFeatures`]
	 * which are broadcasted in our [`NodeAnnouncement`] message.
	 * 
	 * [`NodeAnnouncement`]: crate::ln::msgs::NodeAnnouncement
	 */
	public provided_node_features(): NodeFeatures {
		const ret: bigint = bindings.CustomMessageHandler_provided_node_features(this.ptr);
		const ret_hu_conv: NodeFeatures = new NodeFeatures(null, ret);
		CommonBase.add_ref_from(ret_hu_conv, this);
		return ret_hu_conv;
	}

	/**
	 * Gets the init feature flags which should be sent to the given peer. All available handlers
	 * are queried similarly and their feature flags are OR'd together to form the [`InitFeatures`]
	 * which are sent in our [`Init`] message.
	 * 
	 * [`Init`]: crate::ln::msgs::Init
	 */
	public provided_init_features(their_node_id: Uint8Array): InitFeatures {
		const ret: bigint = bindings.CustomMessageHandler_provided_init_features(this.ptr, bindings.encodeUint8Array(their_node_id));
		const ret_hu_conv: InitFeatures = new InitFeatures(null, ret);
		CommonBase.add_ref_from(ret_hu_conv, this);
		return ret_hu_conv;
	}

}
