
import { CommonBase, UInt5, WitnessVersion, UnqualifiedError } from './CommonBase.mjs';
import * as bindings from '../bindings.mjs'


/**
 * Information communicated in the onion to the recipient for multi-part tracking and proof that
 * the payment is associated with an invoice.
 */
export class FinalOnionHopData extends CommonBase {
	/* @internal */
	public constructor(_dummy: null, ptr: bigint) {
		super(ptr, bindings.FinalOnionHopData_free);
	}

	/**
	 * When sending a multi-part payment, this secret is used to identify a payment across HTLCs.
	 * Because it is generated by the recipient and included in the invoice, it also provides
	 * proof to the recipient that the payment was sent by someone with the generated invoice.
	 */
	public get_payment_secret(): Uint8Array {
		const ret: number = bindings.FinalOnionHopData_get_payment_secret(this.ptr);
		const ret_conv: Uint8Array = bindings.decodeUint8Array(ret);
		return ret_conv;
	}

	/**
	 * When sending a multi-part payment, this secret is used to identify a payment across HTLCs.
	 * Because it is generated by the recipient and included in the invoice, it also provides
	 * proof to the recipient that the payment was sent by someone with the generated invoice.
	 */
	public set_payment_secret(val: Uint8Array): void {
		bindings.FinalOnionHopData_set_payment_secret(this.ptr, bindings.encodeUint8Array(val));
	}

	/**
	 * The intended total amount that this payment is for.
	 * 
	 * Message serialization may panic if this value is more than 21 million Bitcoin.
	 */
	public get_total_msat(): bigint {
		const ret: bigint = bindings.FinalOnionHopData_get_total_msat(this.ptr);
		return ret;
	}

	/**
	 * The intended total amount that this payment is for.
	 * 
	 * Message serialization may panic if this value is more than 21 million Bitcoin.
	 */
	public set_total_msat(val: bigint): void {
		bindings.FinalOnionHopData_set_total_msat(this.ptr, val);
	}

	/**
	 * Constructs a new FinalOnionHopData given each field
	 */
	public static constructor_new(payment_secret_arg: Uint8Array, total_msat_arg: bigint): FinalOnionHopData {
		const ret: bigint = bindings.FinalOnionHopData_new(bindings.encodeUint8Array(payment_secret_arg), total_msat_arg);
		const ret_hu_conv: FinalOnionHopData = new FinalOnionHopData(null, ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	public clone_ptr(): bigint {
		const ret: bigint = bindings.FinalOnionHopData_clone_ptr(this.ptr);
		return ret;
	}

	/**
	 * Creates a copy of the FinalOnionHopData
	 */
	public clone(): FinalOnionHopData {
		const ret: bigint = bindings.FinalOnionHopData_clone(this.ptr);
		const ret_hu_conv: FinalOnionHopData = new FinalOnionHopData(null, ret);
		CommonBase.add_ref_from(ret_hu_conv, this);
		return ret_hu_conv;
	}

	/**
	 * Checks if two FinalOnionHopDatas contain equal inner contents.
	 * This ignores pointers and is_owned flags and looks at the values in fields.
	 * Two objects with NULL inner values will be considered "equal" here.
	 */
	public eq(b: FinalOnionHopData): boolean {
		const ret: boolean = bindings.FinalOnionHopData_eq(this.ptr, CommonBase.get_ptr_of(b));
		return ret;
	}

	/**
	 * Serialize the FinalOnionHopData object into a byte array which can be read by FinalOnionHopData_read
	 */
	public write(): Uint8Array {
		const ret: number = bindings.FinalOnionHopData_write(this.ptr);
		const ret_conv: Uint8Array = bindings.decodeUint8Array(ret);
		return ret_conv;
	}

	/**
	 * Read a FinalOnionHopData from a byte array, created by FinalOnionHopData_write
	 */
	public static constructor_read(ser: Uint8Array): Result_FinalOnionHopDataDecodeErrorZ {
		const ret: bigint = bindings.FinalOnionHopData_read(bindings.encodeUint8Array(ser));
		const ret_hu_conv: Result_FinalOnionHopDataDecodeErrorZ = Result_FinalOnionHopDataDecodeErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

}
