
import { CommonBase, UInt5, WitnessVersion, UnqualifiedError } from './CommonBase.mjs';
import * as bindings from '../bindings.mjs'

/**
 * An event generated by a [`BaseMessageHandler`] which indicates a message should be sent to a
 * peer (or broadcast to most peers).
 * 
 * These events are handled by [`PeerManager::process_events`] if you are using a [`PeerManager`].
 * 
 * [`PeerManager::process_events`]: crate::ln::peer_handler::PeerManager::process_events
 * [`PeerManager`]: crate::ln::peer_handler::PeerManager
 */
export class MessageSendEvent extends CommonBase {
	protected constructor(_dummy: null, ptr: bigint) { super(ptr, bindings.MessageSendEvent_free); }
	/* @internal */
	public static constr_from_ptr(ptr: bigint): MessageSendEvent {
		const raw_ty: number = bindings.LDKMessageSendEvent_ty_from_ptr(ptr);
		switch (raw_ty) {
			case 0: return new MessageSendEvent_SendAcceptChannel(ptr);
			case 1: return new MessageSendEvent_SendAcceptChannelV2(ptr);
			case 2: return new MessageSendEvent_SendOpenChannel(ptr);
			case 3: return new MessageSendEvent_SendOpenChannelV2(ptr);
			case 4: return new MessageSendEvent_SendFundingCreated(ptr);
			case 5: return new MessageSendEvent_SendFundingSigned(ptr);
			case 6: return new MessageSendEvent_SendStfu(ptr);
			case 7: return new MessageSendEvent_SendSpliceInit(ptr);
			case 8: return new MessageSendEvent_SendSpliceAck(ptr);
			case 9: return new MessageSendEvent_SendSpliceLocked(ptr);
			case 10: return new MessageSendEvent_SendTxAddInput(ptr);
			case 11: return new MessageSendEvent_SendTxAddOutput(ptr);
			case 12: return new MessageSendEvent_SendTxRemoveInput(ptr);
			case 13: return new MessageSendEvent_SendTxRemoveOutput(ptr);
			case 14: return new MessageSendEvent_SendTxComplete(ptr);
			case 15: return new MessageSendEvent_SendTxSignatures(ptr);
			case 16: return new MessageSendEvent_SendTxInitRbf(ptr);
			case 17: return new MessageSendEvent_SendTxAckRbf(ptr);
			case 18: return new MessageSendEvent_SendTxAbort(ptr);
			case 19: return new MessageSendEvent_SendChannelReady(ptr);
			case 20: return new MessageSendEvent_SendAnnouncementSignatures(ptr);
			case 21: return new MessageSendEvent_UpdateHTLCs(ptr);
			case 22: return new MessageSendEvent_SendRevokeAndACK(ptr);
			case 23: return new MessageSendEvent_SendClosingSigned(ptr);
			case 24: return new MessageSendEvent_SendClosingComplete(ptr);
			case 25: return new MessageSendEvent_SendClosingSig(ptr);
			case 26: return new MessageSendEvent_SendShutdown(ptr);
			case 27: return new MessageSendEvent_SendChannelReestablish(ptr);
			case 28: return new MessageSendEvent_SendChannelAnnouncement(ptr);
			case 29: return new MessageSendEvent_BroadcastChannelAnnouncement(ptr);
			case 30: return new MessageSendEvent_BroadcastChannelUpdate(ptr);
			case 31: return new MessageSendEvent_BroadcastNodeAnnouncement(ptr);
			case 32: return new MessageSendEvent_SendChannelUpdate(ptr);
			case 33: return new MessageSendEvent_HandleError(ptr);
			case 34: return new MessageSendEvent_SendChannelRangeQuery(ptr);
			case 35: return new MessageSendEvent_SendShortIdsQuery(ptr);
			case 36: return new MessageSendEvent_SendReplyChannelRange(ptr);
			case 37: return new MessageSendEvent_SendGossipTimestampFilter(ptr);
			case 38: return new MessageSendEvent_SendPeerStorage(ptr);
			case 39: return new MessageSendEvent_SendPeerStorageRetrieval(ptr);
			default:
				throw new Error('oops, this should be unreachable'); // Unreachable without extending the (internal) bindings interface
		}
	}

	public clone_ptr(): bigint {
		const ret: bigint = bindings.MessageSendEvent_clone_ptr(this.ptr);
		return ret;
	}

	/**
	 * Creates a copy of the MessageSendEvent
	 */
	public clone(): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_clone(this.ptr);
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, this);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendAcceptChannel-variant MessageSendEvent
	 */
	public static constructor_send_accept_channel(node_id: Uint8Array, msg: AcceptChannel): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_accept_channel(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendAcceptChannelV2-variant MessageSendEvent
	 */
	public static constructor_send_accept_channel_v2(node_id: Uint8Array, msg: AcceptChannelV2): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_accept_channel_v2(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendOpenChannel-variant MessageSendEvent
	 */
	public static constructor_send_open_channel(node_id: Uint8Array, msg: OpenChannel): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_open_channel(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendOpenChannelV2-variant MessageSendEvent
	 */
	public static constructor_send_open_channel_v2(node_id: Uint8Array, msg: OpenChannelV2): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_open_channel_v2(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendFundingCreated-variant MessageSendEvent
	 */
	public static constructor_send_funding_created(node_id: Uint8Array, msg: FundingCreated): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_funding_created(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendFundingSigned-variant MessageSendEvent
	 */
	public static constructor_send_funding_signed(node_id: Uint8Array, msg: FundingSigned): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_funding_signed(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendStfu-variant MessageSendEvent
	 */
	public static constructor_send_stfu(node_id: Uint8Array, msg: Stfu): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_stfu(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendSpliceInit-variant MessageSendEvent
	 */
	public static constructor_send_splice_init(node_id: Uint8Array, msg: SpliceInit): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_splice_init(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendSpliceAck-variant MessageSendEvent
	 */
	public static constructor_send_splice_ack(node_id: Uint8Array, msg: SpliceAck): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_splice_ack(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendSpliceLocked-variant MessageSendEvent
	 */
	public static constructor_send_splice_locked(node_id: Uint8Array, msg: SpliceLocked): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_splice_locked(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendTxAddInput-variant MessageSendEvent
	 */
	public static constructor_send_tx_add_input(node_id: Uint8Array, msg: TxAddInput): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_tx_add_input(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendTxAddOutput-variant MessageSendEvent
	 */
	public static constructor_send_tx_add_output(node_id: Uint8Array, msg: TxAddOutput): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_tx_add_output(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendTxRemoveInput-variant MessageSendEvent
	 */
	public static constructor_send_tx_remove_input(node_id: Uint8Array, msg: TxRemoveInput): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_tx_remove_input(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendTxRemoveOutput-variant MessageSendEvent
	 */
	public static constructor_send_tx_remove_output(node_id: Uint8Array, msg: TxRemoveOutput): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_tx_remove_output(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendTxComplete-variant MessageSendEvent
	 */
	public static constructor_send_tx_complete(node_id: Uint8Array, msg: TxComplete): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_tx_complete(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendTxSignatures-variant MessageSendEvent
	 */
	public static constructor_send_tx_signatures(node_id: Uint8Array, msg: TxSignatures): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_tx_signatures(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendTxInitRbf-variant MessageSendEvent
	 */
	public static constructor_send_tx_init_rbf(node_id: Uint8Array, msg: TxInitRbf): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_tx_init_rbf(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendTxAckRbf-variant MessageSendEvent
	 */
	public static constructor_send_tx_ack_rbf(node_id: Uint8Array, msg: TxAckRbf): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_tx_ack_rbf(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendTxAbort-variant MessageSendEvent
	 */
	public static constructor_send_tx_abort(node_id: Uint8Array, msg: TxAbort): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_tx_abort(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendChannelReady-variant MessageSendEvent
	 */
	public static constructor_send_channel_ready(node_id: Uint8Array, msg: ChannelReady): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_channel_ready(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendAnnouncementSignatures-variant MessageSendEvent
	 */
	public static constructor_send_announcement_signatures(node_id: Uint8Array, msg: AnnouncementSignatures): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_announcement_signatures(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new UpdateHTLCs-variant MessageSendEvent
	 */
	public static constructor_update_htlcs(node_id: Uint8Array, channel_id: ChannelId, updates: CommitmentUpdate): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_update_htlcs(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(channel_id), CommonBase.get_ptr_of(updates));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendRevokeAndACK-variant MessageSendEvent
	 */
	public static constructor_send_revoke_and_ack(node_id: Uint8Array, msg: RevokeAndACK): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_revoke_and_ack(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendClosingSigned-variant MessageSendEvent
	 */
	public static constructor_send_closing_signed(node_id: Uint8Array, msg: ClosingSigned): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_closing_signed(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendClosingComplete-variant MessageSendEvent
	 */
	public static constructor_send_closing_complete(node_id: Uint8Array, msg: ClosingComplete): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_closing_complete(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendClosingSig-variant MessageSendEvent
	 */
	public static constructor_send_closing_sig(node_id: Uint8Array, msg: ClosingSig): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_closing_sig(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendShutdown-variant MessageSendEvent
	 */
	public static constructor_send_shutdown(node_id: Uint8Array, msg: Shutdown): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_shutdown(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendChannelReestablish-variant MessageSendEvent
	 */
	public static constructor_send_channel_reestablish(node_id: Uint8Array, msg: ChannelReestablish): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_channel_reestablish(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendChannelAnnouncement-variant MessageSendEvent
	 */
	public static constructor_send_channel_announcement(node_id: Uint8Array, msg: ChannelAnnouncement, update_msg: ChannelUpdate): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_channel_announcement(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg), CommonBase.get_ptr_of(update_msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new BroadcastChannelAnnouncement-variant MessageSendEvent
	 */
	public static constructor_broadcast_channel_announcement(msg: ChannelAnnouncement, update_msg: ChannelUpdate): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_broadcast_channel_announcement(CommonBase.get_ptr_of(msg), CommonBase.get_ptr_of(update_msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new BroadcastChannelUpdate-variant MessageSendEvent
	 */
	public static constructor_broadcast_channel_update(msg: ChannelUpdate): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_broadcast_channel_update(CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new BroadcastNodeAnnouncement-variant MessageSendEvent
	 */
	public static constructor_broadcast_node_announcement(msg: NodeAnnouncement): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_broadcast_node_announcement(CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendChannelUpdate-variant MessageSendEvent
	 */
	public static constructor_send_channel_update(node_id: Uint8Array, msg: ChannelUpdate): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_channel_update(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new HandleError-variant MessageSendEvent
	 */
	public static constructor_handle_error(node_id: Uint8Array, action: ErrorAction): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_handle_error(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(action));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendChannelRangeQuery-variant MessageSendEvent
	 */
	public static constructor_send_channel_range_query(node_id: Uint8Array, msg: QueryChannelRange): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_channel_range_query(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendShortIdsQuery-variant MessageSendEvent
	 */
	public static constructor_send_short_ids_query(node_id: Uint8Array, msg: QueryShortChannelIds): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_short_ids_query(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendReplyChannelRange-variant MessageSendEvent
	 */
	public static constructor_send_reply_channel_range(node_id: Uint8Array, msg: ReplyChannelRange): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_reply_channel_range(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendGossipTimestampFilter-variant MessageSendEvent
	 */
	public static constructor_send_gossip_timestamp_filter(node_id: Uint8Array, msg: GossipTimestampFilter): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_gossip_timestamp_filter(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendPeerStorage-variant MessageSendEvent
	 */
	public static constructor_send_peer_storage(node_id: Uint8Array, msg: PeerStorage): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_peer_storage(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

	/**
	 * Utility method to constructs a new SendPeerStorageRetrieval-variant MessageSendEvent
	 */
	public static constructor_send_peer_storage_retrieval(node_id: Uint8Array, msg: PeerStorageRetrieval): MessageSendEvent {
		const ret: bigint = bindings.MessageSendEvent_send_peer_storage_retrieval(bindings.encodeUint8Array(node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: MessageSendEvent = MessageSendEvent.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, ret_hu_conv);
		return ret_hu_conv;
	}

}
/** A MessageSendEvent of type SendAcceptChannel */
export class MessageSendEvent_SendAcceptChannel extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: AcceptChannel;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendAcceptChannel_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendAcceptChannel_get_msg(ptr);
		const msg_hu_conv: AcceptChannel = new AcceptChannel(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendAcceptChannelV2 */
export class MessageSendEvent_SendAcceptChannelV2 extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: AcceptChannelV2;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendAcceptChannelV2_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendAcceptChannelV2_get_msg(ptr);
		const msg_hu_conv: AcceptChannelV2 = new AcceptChannelV2(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendOpenChannel */
export class MessageSendEvent_SendOpenChannel extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: OpenChannel;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendOpenChannel_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendOpenChannel_get_msg(ptr);
		const msg_hu_conv: OpenChannel = new OpenChannel(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendOpenChannelV2 */
export class MessageSendEvent_SendOpenChannelV2 extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: OpenChannelV2;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendOpenChannelV2_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendOpenChannelV2_get_msg(ptr);
		const msg_hu_conv: OpenChannelV2 = new OpenChannelV2(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendFundingCreated */
export class MessageSendEvent_SendFundingCreated extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: FundingCreated;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendFundingCreated_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendFundingCreated_get_msg(ptr);
		const msg_hu_conv: FundingCreated = new FundingCreated(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendFundingSigned */
export class MessageSendEvent_SendFundingSigned extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: FundingSigned;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendFundingSigned_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendFundingSigned_get_msg(ptr);
		const msg_hu_conv: FundingSigned = new FundingSigned(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendStfu */
export class MessageSendEvent_SendStfu extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: Stfu;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendStfu_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendStfu_get_msg(ptr);
		const msg_hu_conv: Stfu = new Stfu(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendSpliceInit */
export class MessageSendEvent_SendSpliceInit extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: SpliceInit;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendSpliceInit_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendSpliceInit_get_msg(ptr);
		const msg_hu_conv: SpliceInit = new SpliceInit(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendSpliceAck */
export class MessageSendEvent_SendSpliceAck extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: SpliceAck;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendSpliceAck_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendSpliceAck_get_msg(ptr);
		const msg_hu_conv: SpliceAck = new SpliceAck(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendSpliceLocked */
export class MessageSendEvent_SendSpliceLocked extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: SpliceLocked;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendSpliceLocked_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendSpliceLocked_get_msg(ptr);
		const msg_hu_conv: SpliceLocked = new SpliceLocked(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendTxAddInput */
export class MessageSendEvent_SendTxAddInput extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: TxAddInput;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendTxAddInput_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendTxAddInput_get_msg(ptr);
		const msg_hu_conv: TxAddInput = new TxAddInput(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendTxAddOutput */
export class MessageSendEvent_SendTxAddOutput extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: TxAddOutput;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendTxAddOutput_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendTxAddOutput_get_msg(ptr);
		const msg_hu_conv: TxAddOutput = new TxAddOutput(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendTxRemoveInput */
export class MessageSendEvent_SendTxRemoveInput extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: TxRemoveInput;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendTxRemoveInput_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendTxRemoveInput_get_msg(ptr);
		const msg_hu_conv: TxRemoveInput = new TxRemoveInput(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendTxRemoveOutput */
export class MessageSendEvent_SendTxRemoveOutput extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: TxRemoveOutput;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendTxRemoveOutput_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendTxRemoveOutput_get_msg(ptr);
		const msg_hu_conv: TxRemoveOutput = new TxRemoveOutput(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendTxComplete */
export class MessageSendEvent_SendTxComplete extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: TxComplete;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendTxComplete_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendTxComplete_get_msg(ptr);
		const msg_hu_conv: TxComplete = new TxComplete(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendTxSignatures */
export class MessageSendEvent_SendTxSignatures extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: TxSignatures;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendTxSignatures_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendTxSignatures_get_msg(ptr);
		const msg_hu_conv: TxSignatures = new TxSignatures(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendTxInitRbf */
export class MessageSendEvent_SendTxInitRbf extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: TxInitRbf;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendTxInitRbf_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendTxInitRbf_get_msg(ptr);
		const msg_hu_conv: TxInitRbf = new TxInitRbf(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendTxAckRbf */
export class MessageSendEvent_SendTxAckRbf extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: TxAckRbf;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendTxAckRbf_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendTxAckRbf_get_msg(ptr);
		const msg_hu_conv: TxAckRbf = new TxAckRbf(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendTxAbort */
export class MessageSendEvent_SendTxAbort extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: TxAbort;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendTxAbort_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendTxAbort_get_msg(ptr);
		const msg_hu_conv: TxAbort = new TxAbort(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendChannelReady */
export class MessageSendEvent_SendChannelReady extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive these message(s)
	 */
	public node_id: Uint8Array;
	/**
	 * The channel_ready message which should be sent.
	 */
	public msg: ChannelReady;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendChannelReady_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendChannelReady_get_msg(ptr);
		const msg_hu_conv: ChannelReady = new ChannelReady(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendAnnouncementSignatures */
export class MessageSendEvent_SendAnnouncementSignatures extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive these message(s)
	 */
	public node_id: Uint8Array;
	/**
	 * The announcement_signatures message which should be sent.
	 */
	public msg: AnnouncementSignatures;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendAnnouncementSignatures_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendAnnouncementSignatures_get_msg(ptr);
		const msg_hu_conv: AnnouncementSignatures = new AnnouncementSignatures(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type UpdateHTLCs */
export class MessageSendEvent_UpdateHTLCs extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive these message(s)
	 */
	public node_id: Uint8Array;
	/**
	 * The channel_id associated with all the update messages.
	 */
	public channel_id: ChannelId;
	/**
	 * The update messages which should be sent. ALL messages in the struct should be sent!
	 */
	public updates: CommitmentUpdate;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_UpdateHTLCs_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const channel_id: bigint = bindings.LDKMessageSendEvent_UpdateHTLCs_get_channel_id(ptr);
		const channel_id_hu_conv: ChannelId = new ChannelId(null, channel_id);
			CommonBase.add_ref_from(channel_id_hu_conv, this);
		this.channel_id = channel_id_hu_conv;
		const updates: bigint = bindings.LDKMessageSendEvent_UpdateHTLCs_get_updates(ptr);
		const updates_hu_conv: CommitmentUpdate = new CommitmentUpdate(null, updates);
			CommonBase.add_ref_from(updates_hu_conv, this);
		this.updates = updates_hu_conv;
	}
}
/** A MessageSendEvent of type SendRevokeAndACK */
export class MessageSendEvent_SendRevokeAndACK extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: RevokeAndACK;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendRevokeAndACK_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendRevokeAndACK_get_msg(ptr);
		const msg_hu_conv: RevokeAndACK = new RevokeAndACK(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendClosingSigned */
export class MessageSendEvent_SendClosingSigned extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: ClosingSigned;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendClosingSigned_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendClosingSigned_get_msg(ptr);
		const msg_hu_conv: ClosingSigned = new ClosingSigned(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendClosingComplete */
export class MessageSendEvent_SendClosingComplete extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: ClosingComplete;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendClosingComplete_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendClosingComplete_get_msg(ptr);
		const msg_hu_conv: ClosingComplete = new ClosingComplete(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendClosingSig */
export class MessageSendEvent_SendClosingSig extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: ClosingSig;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendClosingSig_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendClosingSig_get_msg(ptr);
		const msg_hu_conv: ClosingSig = new ClosingSig(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendShutdown */
export class MessageSendEvent_SendShutdown extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: Shutdown;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendShutdown_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendShutdown_get_msg(ptr);
		const msg_hu_conv: Shutdown = new Shutdown(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendChannelReestablish */
export class MessageSendEvent_SendChannelReestablish extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The message which should be sent.
	 */
	public msg: ChannelReestablish;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendChannelReestablish_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendChannelReestablish_get_msg(ptr);
		const msg_hu_conv: ChannelReestablish = new ChannelReestablish(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendChannelAnnouncement */
export class MessageSendEvent_SendChannelAnnouncement extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The channel_announcement which should be sent.
	 */
	public msg: ChannelAnnouncement;
	/**
	 * The followup channel_update which should be sent.
	 */
	public update_msg: ChannelUpdate;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendChannelAnnouncement_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendChannelAnnouncement_get_msg(ptr);
		const msg_hu_conv: ChannelAnnouncement = new ChannelAnnouncement(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
		const update_msg: bigint = bindings.LDKMessageSendEvent_SendChannelAnnouncement_get_update_msg(ptr);
		const update_msg_hu_conv: ChannelUpdate = new ChannelUpdate(null, update_msg);
			CommonBase.add_ref_from(update_msg_hu_conv, this);
		this.update_msg = update_msg_hu_conv;
	}
}
/** A MessageSendEvent of type BroadcastChannelAnnouncement */
export class MessageSendEvent_BroadcastChannelAnnouncement extends MessageSendEvent {
	/**
	 * The channel_announcement which should be sent.
	 */
	public msg: ChannelAnnouncement;
	/**
	 * The followup channel_update which should be sent.
	 * 
	 * Note that this (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	public update_msg: ChannelUpdate;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const msg: bigint = bindings.LDKMessageSendEvent_BroadcastChannelAnnouncement_get_msg(ptr);
		const msg_hu_conv: ChannelAnnouncement = new ChannelAnnouncement(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
		const update_msg: bigint = bindings.LDKMessageSendEvent_BroadcastChannelAnnouncement_get_update_msg(ptr);
		const update_msg_hu_conv: ChannelUpdate = new ChannelUpdate(null, update_msg);
			CommonBase.add_ref_from(update_msg_hu_conv, this);
		this.update_msg = update_msg_hu_conv;
	}
}
/** A MessageSendEvent of type BroadcastChannelUpdate */
export class MessageSendEvent_BroadcastChannelUpdate extends MessageSendEvent {
	/**
	 * The channel_update which should be sent.
	 */
	public msg: ChannelUpdate;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const msg: bigint = bindings.LDKMessageSendEvent_BroadcastChannelUpdate_get_msg(ptr);
		const msg_hu_conv: ChannelUpdate = new ChannelUpdate(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type BroadcastNodeAnnouncement */
export class MessageSendEvent_BroadcastNodeAnnouncement extends MessageSendEvent {
	/**
	 * The node_announcement which should be sent.
	 */
	public msg: NodeAnnouncement;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const msg: bigint = bindings.LDKMessageSendEvent_BroadcastNodeAnnouncement_get_msg(ptr);
		const msg_hu_conv: NodeAnnouncement = new NodeAnnouncement(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendChannelUpdate */
export class MessageSendEvent_SendChannelUpdate extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The channel_update which should be sent.
	 */
	public msg: ChannelUpdate;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendChannelUpdate_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendChannelUpdate_get_msg(ptr);
		const msg_hu_conv: ChannelUpdate = new ChannelUpdate(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type HandleError */
export class MessageSendEvent_HandleError extends MessageSendEvent {
	/**
	 * The node_id of the node which should receive this message
	 */
	public node_id: Uint8Array;
	/**
	 * The action which should be taken.
	 */
	public action: ErrorAction;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_HandleError_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const action: bigint = bindings.LDKMessageSendEvent_HandleError_get_action(ptr);
		const action_hu_conv: ErrorAction = ErrorAction.constr_from_ptr(action);
			CommonBase.add_ref_from(action_hu_conv, this);
		this.action = action_hu_conv;
	}
}
/** A MessageSendEvent of type SendChannelRangeQuery */
export class MessageSendEvent_SendChannelRangeQuery extends MessageSendEvent {
	/**
	 * The node_id of this message recipient
	 */
	public node_id: Uint8Array;
	/**
	 * The query_channel_range which should be sent.
	 */
	public msg: QueryChannelRange;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendChannelRangeQuery_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendChannelRangeQuery_get_msg(ptr);
		const msg_hu_conv: QueryChannelRange = new QueryChannelRange(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendShortIdsQuery */
export class MessageSendEvent_SendShortIdsQuery extends MessageSendEvent {
	/**
	 * The node_id of this message recipient
	 */
	public node_id: Uint8Array;
	/**
	 * The query_short_channel_ids which should be sent.
	 */
	public msg: QueryShortChannelIds;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendShortIdsQuery_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendShortIdsQuery_get_msg(ptr);
		const msg_hu_conv: QueryShortChannelIds = new QueryShortChannelIds(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendReplyChannelRange */
export class MessageSendEvent_SendReplyChannelRange extends MessageSendEvent {
	/**
	 * The node_id of this message recipient
	 */
	public node_id: Uint8Array;
	/**
	 * The reply_channel_range which should be sent.
	 */
	public msg: ReplyChannelRange;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendReplyChannelRange_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendReplyChannelRange_get_msg(ptr);
		const msg_hu_conv: ReplyChannelRange = new ReplyChannelRange(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendGossipTimestampFilter */
export class MessageSendEvent_SendGossipTimestampFilter extends MessageSendEvent {
	/**
	 * The node_id of this message recipient
	 */
	public node_id: Uint8Array;
	/**
	 * The gossip_timestamp_filter which should be sent.
	 */
	public msg: GossipTimestampFilter;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendGossipTimestampFilter_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendGossipTimestampFilter_get_msg(ptr);
		const msg_hu_conv: GossipTimestampFilter = new GossipTimestampFilter(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendPeerStorage */
export class MessageSendEvent_SendPeerStorage extends MessageSendEvent {
	/**
	 * The node_id of this message recipient
	 */
	public node_id: Uint8Array;
	/**
	 * The peer_storage which should be sent.
	 */
	public msg: PeerStorage;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendPeerStorage_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendPeerStorage_get_msg(ptr);
		const msg_hu_conv: PeerStorage = new PeerStorage(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
/** A MessageSendEvent of type SendPeerStorageRetrieval */
export class MessageSendEvent_SendPeerStorageRetrieval extends MessageSendEvent {
	/**
	 * The node_id of this message recipient
	 */
	public node_id: Uint8Array;
	/**
	 * The peer_storage_retrieval which should be sent.
	 */
	public msg: PeerStorageRetrieval;
	/* @internal */
	public constructor(ptr: bigint) {
		super(null, ptr);
		const node_id: number = bindings.LDKMessageSendEvent_SendPeerStorageRetrieval_get_node_id(ptr);
		const node_id_conv: Uint8Array = bindings.decodeUint8Array(node_id);
		this.node_id = node_id_conv;
		const msg: bigint = bindings.LDKMessageSendEvent_SendPeerStorageRetrieval_get_msg(ptr);
		const msg_hu_conv: PeerStorageRetrieval = new PeerStorageRetrieval(null, msg);
			CommonBase.add_ref_from(msg_hu_conv, this);
		this.msg = msg_hu_conv;
	}
}
