

import { CommonBase, UInt5, WitnessVersion, UnqualifiedError } from './CommonBase.mjs';
import * as bindings from '../bindings.mjs'



/** An implementation of RoutingMessageHandler */
export interface RoutingMessageHandlerInterface {
	/**Handle an incoming `node_announcement` message, returning `true` if it should be forwarded on,
	 * `false` or returning an `Err` otherwise.
	 * 
	 * If `their_node_id` is `None`, the message was generated by our own local node.
	 * 
	 * Note that their_node_id (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	handle_node_announcement(their_node_id: Uint8Array, msg: NodeAnnouncement): Result_boolLightningErrorZ;
	/**Handle a `channel_announcement` message, returning `true` if it should be forwarded on, `false`
	 * or returning an `Err` otherwise.
	 * 
	 * If `their_node_id` is `None`, the message was generated by our own local node.
	 * 
	 * Note that their_node_id (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	handle_channel_announcement(their_node_id: Uint8Array, msg: ChannelAnnouncement): Result_boolLightningErrorZ;
	/**Handle an incoming `channel_update` message, returning true if it should be forwarded on,
	 * `false` or returning an `Err` otherwise.
	 * 
	 * If `their_node_id` is `None`, the message was generated by our own local node.
	 * 
	 * Note that their_node_id (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	handle_channel_update(their_node_id: Uint8Array, msg: ChannelUpdate): Result_boolLightningErrorZ;
	/**Gets channel announcements and updates required to dump our routing table to a remote node,
	 * starting at the `short_channel_id` indicated by `starting_point` and including announcements
	 * for a single channel.
	 */
	get_next_channel_announcement(starting_point: bigint): Option_C3Tuple_ChannelAnnouncementChannelUpdateChannelUpdateZZ;
	/**Gets a node announcement required to dump our routing table to a remote node, starting at
	 * the node *after* the provided pubkey and including up to one announcement immediately
	 * higher (as defined by `<PublicKey as Ord>::cmp`) than `starting_point`.
	 * If `None` is provided for `starting_point`, we start at the first node.
	 * 
	 * Note that starting_point (or a relevant inner pointer) may be NULL or all-0s to represent None
	 * Note that the return value (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	get_next_node_announcement(starting_point: NodeId): NodeAnnouncement;
	/**Handles the reply of a query we initiated to learn about channels
	 * for a given range of blocks. We can expect to receive one or more
	 * replies to a single query.
	 */
	handle_reply_channel_range(their_node_id: Uint8Array, msg: ReplyChannelRange): Result_NoneLightningErrorZ;
	/**Handles the reply of a query we initiated asking for routing gossip
	 * messages for a list of channels. We should receive this message when
	 * a node has completed its best effort to send us the pertaining routing
	 * gossip messages.
	 */
	handle_reply_short_channel_ids_end(their_node_id: Uint8Array, msg: ReplyShortChannelIdsEnd): Result_NoneLightningErrorZ;
	/**Handles when a peer asks us to send a list of `short_channel_id`s
	 * for the requested range of blocks.
	 */
	handle_query_channel_range(their_node_id: Uint8Array, msg: QueryChannelRange): Result_NoneLightningErrorZ;
	/**Handles when a peer asks us to send routing gossip messages for a
	 * list of `short_channel_id`s.
	 */
	handle_query_short_channel_ids(their_node_id: Uint8Array, msg: QueryShortChannelIds): Result_NoneLightningErrorZ;
	/**Indicates that there are a large number of [`ChannelAnnouncement`] (or other) messages
	 * pending some async action. While there is no guarantee of the rate of future messages, the
	 * caller should seek to reduce the rate of new gossip messages handled, especially
	 * [`ChannelAnnouncement`]s.
	 */
	processing_queue_high(): boolean;
}

class LDKRoutingMessageHandlerHolder {
	held: RoutingMessageHandler|null = null;
}

/**
 * A trait to describe an object which can receive routing messages.
 * 
 * # Implementor DoS Warnings
 * 
 * For messages enabled with the `gossip_queries` feature there are potential DoS vectors when
 * handling inbound queries. Implementors using an on-disk network graph should be aware of
 * repeated disk I/O for queries accessing different parts of the network graph.
 */
export class RoutingMessageHandler extends CommonBase {
	/* @internal */
	public bindings_instance: bindings.LDKRoutingMessageHandler|null;

	/* @internal */
	public instance_idx?: number;

	/* @internal */
	constructor(_dummy: null, ptr: bigint) {
		super(ptr, bindings.RoutingMessageHandler_free);
		this.bindings_instance = null;
	}

	/** Creates a new instance of RoutingMessageHandler from a given implementation */
	public static new_impl(arg: RoutingMessageHandlerInterface, baseMessageHandler_impl: BaseMessageHandlerInterface): RoutingMessageHandler {
		const impl_holder: LDKRoutingMessageHandlerHolder = new LDKRoutingMessageHandlerHolder();
		let structImplementation = {
			handle_node_announcement (their_node_id: number, msg: bigint): bigint {
				const their_node_id_conv: Uint8Array = bindings.decodeUint8Array(their_node_id);
				const msg_hu_conv: NodeAnnouncement = new NodeAnnouncement(null, msg);
				const ret: Result_boolLightningErrorZ = arg.handle_node_announcement(their_node_id_conv, msg_hu_conv);
				const result: bigint = ret.clone_ptr();
				return result;
			},
			handle_channel_announcement (their_node_id: number, msg: bigint): bigint {
				const their_node_id_conv: Uint8Array = bindings.decodeUint8Array(their_node_id);
				const msg_hu_conv: ChannelAnnouncement = new ChannelAnnouncement(null, msg);
				const ret: Result_boolLightningErrorZ = arg.handle_channel_announcement(their_node_id_conv, msg_hu_conv);
				const result: bigint = ret.clone_ptr();
				return result;
			},
			handle_channel_update (their_node_id: number, msg: bigint): bigint {
				const their_node_id_conv: Uint8Array = bindings.decodeUint8Array(their_node_id);
				const msg_hu_conv: ChannelUpdate = new ChannelUpdate(null, msg);
				const ret: Result_boolLightningErrorZ = arg.handle_channel_update(their_node_id_conv, msg_hu_conv);
				const result: bigint = ret.clone_ptr();
				return result;
			},
			get_next_channel_announcement (starting_point: bigint): bigint {
				const ret: Option_C3Tuple_ChannelAnnouncementChannelUpdateChannelUpdateZZ = arg.get_next_channel_announcement(starting_point);
				const result: bigint = ret.clone_ptr();
				return result;
			},
			get_next_node_announcement (starting_point: bigint): bigint {
				const starting_point_hu_conv: NodeId = new NodeId(null, starting_point);
				CommonBase.add_ref_from(starting_point_hu_conv, this);
				const ret: NodeAnnouncement = arg.get_next_node_announcement(starting_point_hu_conv);
				const result: bigint = ret == null ? 0n : ret.clone_ptr();
				return result;
			},
			handle_reply_channel_range (their_node_id: number, msg: bigint): bigint {
				const their_node_id_conv: Uint8Array = bindings.decodeUint8Array(their_node_id);
				const msg_hu_conv: ReplyChannelRange = new ReplyChannelRange(null, msg);
				CommonBase.add_ref_from(msg_hu_conv, this);
				const ret: Result_NoneLightningErrorZ = arg.handle_reply_channel_range(their_node_id_conv, msg_hu_conv);
				const result: bigint = ret.clone_ptr();
				return result;
			},
			handle_reply_short_channel_ids_end (their_node_id: number, msg: bigint): bigint {
				const their_node_id_conv: Uint8Array = bindings.decodeUint8Array(their_node_id);
				const msg_hu_conv: ReplyShortChannelIdsEnd = new ReplyShortChannelIdsEnd(null, msg);
				CommonBase.add_ref_from(msg_hu_conv, this);
				const ret: Result_NoneLightningErrorZ = arg.handle_reply_short_channel_ids_end(their_node_id_conv, msg_hu_conv);
				const result: bigint = ret.clone_ptr();
				return result;
			},
			handle_query_channel_range (their_node_id: number, msg: bigint): bigint {
				const their_node_id_conv: Uint8Array = bindings.decodeUint8Array(their_node_id);
				const msg_hu_conv: QueryChannelRange = new QueryChannelRange(null, msg);
				CommonBase.add_ref_from(msg_hu_conv, this);
				const ret: Result_NoneLightningErrorZ = arg.handle_query_channel_range(their_node_id_conv, msg_hu_conv);
				const result: bigint = ret.clone_ptr();
				return result;
			},
			handle_query_short_channel_ids (their_node_id: number, msg: bigint): bigint {
				const their_node_id_conv: Uint8Array = bindings.decodeUint8Array(their_node_id);
				const msg_hu_conv: QueryShortChannelIds = new QueryShortChannelIds(null, msg);
				CommonBase.add_ref_from(msg_hu_conv, this);
				const ret: Result_NoneLightningErrorZ = arg.handle_query_short_channel_ids(their_node_id_conv, msg_hu_conv);
				const result: bigint = ret.clone_ptr();
				return result;
			},
			processing_queue_high (): boolean {
				const ret: boolean = arg.processing_queue_high();
				return ret;
			},
		} as bindings.LDKRoutingMessageHandler;
		const baseMessageHandler = BaseMessageHandler.new_impl(baseMessageHandler_impl);
		const ptr_idx: [bigint, number] = bindings.LDKRoutingMessageHandler_new(structImplementation, baseMessageHandler.instance_idx!);

		impl_holder.held = new RoutingMessageHandler(null, ptr_idx[0]);
		impl_holder.held.instance_idx = ptr_idx[1];
		impl_holder.held.bindings_instance = structImplementation;
		impl_holder.held.ptrs_to.push(baseMessageHandler);
		return impl_holder.held!;
	}

	/**
	 * Handle an incoming `node_announcement` message, returning `true` if it should be forwarded on,
	 * `false` or returning an `Err` otherwise.
	 * 
	 * If `their_node_id` is `None`, the message was generated by our own local node.
	 * 
	 * Note that their_node_id (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	public handle_node_announcement(their_node_id: Uint8Array|null, msg: NodeAnnouncement): Result_boolLightningErrorZ {
		const ret: bigint = bindings.RoutingMessageHandler_handle_node_announcement(this.ptr, bindings.encodeUint8Array(their_node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: Result_boolLightningErrorZ = Result_boolLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Handle a `channel_announcement` message, returning `true` if it should be forwarded on, `false`
	 * or returning an `Err` otherwise.
	 * 
	 * If `their_node_id` is `None`, the message was generated by our own local node.
	 * 
	 * Note that their_node_id (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	public handle_channel_announcement(their_node_id: Uint8Array|null, msg: ChannelAnnouncement): Result_boolLightningErrorZ {
		const ret: bigint = bindings.RoutingMessageHandler_handle_channel_announcement(this.ptr, bindings.encodeUint8Array(their_node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: Result_boolLightningErrorZ = Result_boolLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Handle an incoming `channel_update` message, returning true if it should be forwarded on,
	 * `false` or returning an `Err` otherwise.
	 * 
	 * If `their_node_id` is `None`, the message was generated by our own local node.
	 * 
	 * Note that their_node_id (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	public handle_channel_update(their_node_id: Uint8Array|null, msg: ChannelUpdate): Result_boolLightningErrorZ {
		const ret: bigint = bindings.RoutingMessageHandler_handle_channel_update(this.ptr, bindings.encodeUint8Array(their_node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: Result_boolLightningErrorZ = Result_boolLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Gets channel announcements and updates required to dump our routing table to a remote node,
	 * starting at the `short_channel_id` indicated by `starting_point` and including announcements
	 * for a single channel.
	 */
	public get_next_channel_announcement(starting_point: bigint): Option_C3Tuple_ChannelAnnouncementChannelUpdateChannelUpdateZZ {
		const ret: bigint = bindings.RoutingMessageHandler_get_next_channel_announcement(this.ptr, starting_point);
		const ret_hu_conv: Option_C3Tuple_ChannelAnnouncementChannelUpdateChannelUpdateZZ = Option_C3Tuple_ChannelAnnouncementChannelUpdateChannelUpdateZZ.constr_from_ptr(ret);
		CommonBase.add_ref_from(ret_hu_conv, this);
		return ret_hu_conv;
	}

	/**
	 * Gets a node announcement required to dump our routing table to a remote node, starting at
	 * the node *after* the provided pubkey and including up to one announcement immediately
	 * higher (as defined by `<PublicKey as Ord>::cmp`) than `starting_point`.
	 * If `None` is provided for `starting_point`, we start at the first node.
	 * 
	 * Note that starting_point (or a relevant inner pointer) may be NULL or all-0s to represent None
	 * Note that the return value (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	public get_next_node_announcement(starting_point: NodeId|null): NodeAnnouncement {
		const ret: bigint = bindings.RoutingMessageHandler_get_next_node_announcement(this.ptr, starting_point == null ? 0n : CommonBase.get_ptr_of(starting_point));
		const ret_hu_conv: NodeAnnouncement = new NodeAnnouncement(null, ret);
		CommonBase.add_ref_from(ret_hu_conv, this);
		return ret_hu_conv;
	}

	/**
	 * Handles the reply of a query we initiated to learn about channels
	 * for a given range of blocks. We can expect to receive one or more
	 * replies to a single query.
	 */
	public handle_reply_channel_range(their_node_id: Uint8Array, msg: ReplyChannelRange): Result_NoneLightningErrorZ {
		const ret: bigint = bindings.RoutingMessageHandler_handle_reply_channel_range(this.ptr, bindings.encodeUint8Array(their_node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: Result_NoneLightningErrorZ = Result_NoneLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Handles the reply of a query we initiated asking for routing gossip
	 * messages for a list of channels. We should receive this message when
	 * a node has completed its best effort to send us the pertaining routing
	 * gossip messages.
	 */
	public handle_reply_short_channel_ids_end(their_node_id: Uint8Array, msg: ReplyShortChannelIdsEnd): Result_NoneLightningErrorZ {
		const ret: bigint = bindings.RoutingMessageHandler_handle_reply_short_channel_ids_end(this.ptr, bindings.encodeUint8Array(their_node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: Result_NoneLightningErrorZ = Result_NoneLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Handles when a peer asks us to send a list of `short_channel_id`s
	 * for the requested range of blocks.
	 */
	public handle_query_channel_range(their_node_id: Uint8Array, msg: QueryChannelRange): Result_NoneLightningErrorZ {
		const ret: bigint = bindings.RoutingMessageHandler_handle_query_channel_range(this.ptr, bindings.encodeUint8Array(their_node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: Result_NoneLightningErrorZ = Result_NoneLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Handles when a peer asks us to send routing gossip messages for a
	 * list of `short_channel_id`s.
	 */
	public handle_query_short_channel_ids(their_node_id: Uint8Array, msg: QueryShortChannelIds): Result_NoneLightningErrorZ {
		const ret: bigint = bindings.RoutingMessageHandler_handle_query_short_channel_ids(this.ptr, bindings.encodeUint8Array(their_node_id), CommonBase.get_ptr_of(msg));
		const ret_hu_conv: Result_NoneLightningErrorZ = Result_NoneLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Indicates that there are a large number of [`ChannelAnnouncement`] (or other) messages
	 * pending some async action. While there is no guarantee of the rate of future messages, the
	 * caller should seek to reduce the rate of new gossip messages handled, especially
	 * [`ChannelAnnouncement`]s.
	 */
	public processing_queue_high(): boolean {
		const ret: boolean = bindings.RoutingMessageHandler_processing_queue_high(this.ptr);
		return ret;
	}

}
