/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ldk_impl_bindings_LDKSpendableOutputDescriptor_DynamicOutputP2WSH */

#ifndef _Included_org_ldk_impl_bindings_LDKSpendableOutputDescriptor_DynamicOutputP2WSH
#define _Included_org_ldk_impl_bindings_LDKSpendableOutputDescriptor_DynamicOutputP2WSH
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ldk_impl_bindings_LDKSpendableOutputDescriptor_DynamicOutputP2WSH
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ldk_impl_bindings_00024LDKSpendableOutputDescriptor_00024DynamicOutputP2WSH_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
