/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ldk_impl_bindings_LDKNetAddress_IPv6 */

#ifndef _Included_org_ldk_impl_bindings_LDKNetAddress_IPv6
#define _Included_org_ldk_impl_bindings_LDKNetAddress_IPv6
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ldk_impl_bindings_LDKNetAddress_IPv6
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ldk_impl_bindings_00024LDKNetAddress_00024IPv6_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
