/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ldk_impl_bindings_LDKCOption_CVec_u8ZZ */

#ifndef _Included_org_ldk_impl_bindings_LDKCOption_CVec_u8ZZ
#define _Included_org_ldk_impl_bindings_LDKCOption_CVec_u8ZZ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ldk_impl_bindings_LDKCOption_CVec_u8ZZ
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ldk_impl_bindings_00024LDKCOption_1CVec_1u8ZZ_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
