/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ldk_impl_bindings_LDKMessageSendEvent_SendShutdown */

#ifndef _Included_org_ldk_impl_bindings_LDKMessageSendEvent_SendShutdown
#define _Included_org_ldk_impl_bindings_LDKMessageSendEvent_SendShutdown
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ldk_impl_bindings_LDKMessageSendEvent_SendShutdown
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ldk_impl_bindings_00024LDKMessageSendEvent_00024SendShutdown_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
