/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ldk_impl_bindings_LDKDestination */

#ifndef _Included_org_ldk_impl_bindings_LDKDestination
#define _Included_org_ldk_impl_bindings_LDKDestination
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ldk_impl_bindings_LDKDestination
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ldk_impl_bindings_00024LDKDestination_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
