/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ldk_impl_bindings_LDKCOption_U128Z */

#ifndef _Included_org_ldk_impl_bindings_LDKCOption_U128Z
#define _Included_org_ldk_impl_bindings_LDKCOption_U128Z
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ldk_impl_bindings_LDKCOption_U128Z
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ldk_impl_bindings_00024LDKCOption_1U128Z_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
