
using org.ldk.impl;
using org.ldk.enums;
using org.ldk.util;
using System;

namespace org { namespace ldk { namespace structs {



/** An implementation of RoutingMessageHandler */
public interface RoutingMessageHandlerInterface {
	/**Handle an incoming `node_announcement` message, returning `true` if it should be forwarded on,
	 * `false` or returning an `Err` otherwise.
	 * 
	 * If `their_node_id` is `None`, the message was generated by our own local node.
	 * 
	 * Note that their_node_id (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	Result_boolLightningErrorZ handle_node_announcement(byte[] their_node_id, org.ldk.structs.NodeAnnouncement msg);
	/**Handle a `channel_announcement` message, returning `true` if it should be forwarded on, `false`
	 * or returning an `Err` otherwise.
	 * 
	 * If `their_node_id` is `None`, the message was generated by our own local node.
	 * 
	 * Note that their_node_id (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	Result_boolLightningErrorZ handle_channel_announcement(byte[] their_node_id, org.ldk.structs.ChannelAnnouncement msg);
	/**Handle an incoming `channel_update` message, returning true if it should be forwarded on,
	 * `false` or returning an `Err` otherwise.
	 * 
	 * If `their_node_id` is `None`, the message was generated by our own local node.
	 * 
	 * Note that their_node_id (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	Result_boolLightningErrorZ handle_channel_update(byte[] their_node_id, org.ldk.structs.ChannelUpdate msg);
	/**Gets channel announcements and updates required to dump our routing table to a remote node,
	 * starting at the `short_channel_id` indicated by `starting_point` and including announcements
	 * for a single channel.
	 */
	Option_C3Tuple_ChannelAnnouncementChannelUpdateChannelUpdateZZ get_next_channel_announcement(long starting_point);
	/**Gets a node announcement required to dump our routing table to a remote node, starting at
	 * the node *after* the provided pubkey and including up to one announcement immediately
	 * higher (as defined by `<PublicKey as Ord>::cmp`) than `starting_point`.
	 * If `None` is provided for `starting_point`, we start at the first node.
	 * 
	 * Note that starting_point (or a relevant inner pointer) may be NULL or all-0s to represent None
	 * Note that the return value (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	NodeAnnouncement get_next_node_announcement(org.ldk.structs.NodeId starting_point);
	/**Handles the reply of a query we initiated to learn about channels
	 * for a given range of blocks. We can expect to receive one or more
	 * replies to a single query.
	 */
	Result_NoneLightningErrorZ handle_reply_channel_range(byte[] their_node_id, org.ldk.structs.ReplyChannelRange msg);
	/**Handles the reply of a query we initiated asking for routing gossip
	 * messages for a list of channels. We should receive this message when
	 * a node has completed its best effort to send us the pertaining routing
	 * gossip messages.
	 */
	Result_NoneLightningErrorZ handle_reply_short_channel_ids_end(byte[] their_node_id, org.ldk.structs.ReplyShortChannelIdsEnd msg);
	/**Handles when a peer asks us to send a list of `short_channel_id`s
	 * for the requested range of blocks.
	 */
	Result_NoneLightningErrorZ handle_query_channel_range(byte[] their_node_id, org.ldk.structs.QueryChannelRange msg);
	/**Handles when a peer asks us to send routing gossip messages for a
	 * list of `short_channel_id`s.
	 */
	Result_NoneLightningErrorZ handle_query_short_channel_ids(byte[] their_node_id, org.ldk.structs.QueryShortChannelIds msg);
	/**Indicates that there are a large number of [`ChannelAnnouncement`] (or other) messages
	 * pending some async action. While there is no guarantee of the rate of future messages, the
	 * caller should seek to reduce the rate of new gossip messages handled, especially
	 * [`ChannelAnnouncement`]s.
	 */
	bool processing_queue_high();
}

/**
 * A trait to describe an object which can receive routing messages.
 * 
 * # Implementor DoS Warnings
 * 
 * For messages enabled with the `gossip_queries` feature there are potential DoS vectors when
 * handling inbound queries. Implementors using an on-disk network graph should be aware of
 * repeated disk I/O for queries accessing different parts of the network graph.
 */
public class RoutingMessageHandler : CommonBase {
	internal bindings.LDKRoutingMessageHandler bindings_instance;
	internal long instance_idx;

	internal RoutingMessageHandler(object _dummy, long ptr) : base(ptr) { bindings_instance = null; }
	~RoutingMessageHandler() {
		if (ptr != 0) { bindings.RoutingMessageHandler_free(ptr); }
	}

	private class LDKRoutingMessageHandlerHolder { internal RoutingMessageHandler held; }
	private class LDKRoutingMessageHandlerImpl : bindings.LDKRoutingMessageHandler {
		internal LDKRoutingMessageHandlerImpl(RoutingMessageHandlerInterface arg, LDKRoutingMessageHandlerHolder impl_holder) { this.arg = arg; this.impl_holder = impl_holder; }
		private RoutingMessageHandlerInterface arg;
		private LDKRoutingMessageHandlerHolder impl_holder;
		public long handle_node_announcement(long _their_node_id, long _msg) {
			byte[] _their_node_id_conv = InternalUtils.decodeUint8Array(_their_node_id);
			org.ldk.structs.NodeAnnouncement _msg_hu_conv = null; if (_msg < 0 || _msg > 4096) { _msg_hu_conv = new org.ldk.structs.NodeAnnouncement(null, _msg); }
			Result_boolLightningErrorZ ret = arg.handle_node_announcement(_their_node_id_conv, _msg_hu_conv);
				GC.KeepAlive(arg);
			long result = ret.clone_ptr();
			return result;
		}
		public long handle_channel_announcement(long _their_node_id, long _msg) {
			byte[] _their_node_id_conv = InternalUtils.decodeUint8Array(_their_node_id);
			org.ldk.structs.ChannelAnnouncement _msg_hu_conv = null; if (_msg < 0 || _msg > 4096) { _msg_hu_conv = new org.ldk.structs.ChannelAnnouncement(null, _msg); }
			Result_boolLightningErrorZ ret = arg.handle_channel_announcement(_their_node_id_conv, _msg_hu_conv);
				GC.KeepAlive(arg);
			long result = ret.clone_ptr();
			return result;
		}
		public long handle_channel_update(long _their_node_id, long _msg) {
			byte[] _their_node_id_conv = InternalUtils.decodeUint8Array(_their_node_id);
			org.ldk.structs.ChannelUpdate _msg_hu_conv = null; if (_msg < 0 || _msg > 4096) { _msg_hu_conv = new org.ldk.structs.ChannelUpdate(null, _msg); }
			Result_boolLightningErrorZ ret = arg.handle_channel_update(_their_node_id_conv, _msg_hu_conv);
				GC.KeepAlive(arg);
			long result = ret.clone_ptr();
			return result;
		}
		public long get_next_channel_announcement(long _starting_point) {
			Option_C3Tuple_ChannelAnnouncementChannelUpdateChannelUpdateZZ ret = arg.get_next_channel_announcement(_starting_point);
				GC.KeepAlive(arg);
			long result = ret.clone_ptr();
			return result;
		}
		public long get_next_node_announcement(long _starting_point) {
			org.ldk.structs.NodeId _starting_point_hu_conv = null; if (_starting_point < 0 || _starting_point > 4096) { _starting_point_hu_conv = new org.ldk.structs.NodeId(null, _starting_point); }
			if (_starting_point_hu_conv != null) { _starting_point_hu_conv.ptrs_to.AddLast(this); };
			NodeAnnouncement ret = arg.get_next_node_announcement(_starting_point_hu_conv);
				GC.KeepAlive(arg);
			long result = ret == null ? 0 : ret.clone_ptr();
			return result;
		}
		public long handle_reply_channel_range(long _their_node_id, long _msg) {
			byte[] _their_node_id_conv = InternalUtils.decodeUint8Array(_their_node_id);
			org.ldk.structs.ReplyChannelRange _msg_hu_conv = null; if (_msg < 0 || _msg > 4096) { _msg_hu_conv = new org.ldk.structs.ReplyChannelRange(null, _msg); }
			if (_msg_hu_conv != null) { _msg_hu_conv.ptrs_to.AddLast(this); };
			Result_NoneLightningErrorZ ret = arg.handle_reply_channel_range(_their_node_id_conv, _msg_hu_conv);
				GC.KeepAlive(arg);
			long result = ret.clone_ptr();
			return result;
		}
		public long handle_reply_short_channel_ids_end(long _their_node_id, long _msg) {
			byte[] _their_node_id_conv = InternalUtils.decodeUint8Array(_their_node_id);
			org.ldk.structs.ReplyShortChannelIdsEnd _msg_hu_conv = null; if (_msg < 0 || _msg > 4096) { _msg_hu_conv = new org.ldk.structs.ReplyShortChannelIdsEnd(null, _msg); }
			if (_msg_hu_conv != null) { _msg_hu_conv.ptrs_to.AddLast(this); };
			Result_NoneLightningErrorZ ret = arg.handle_reply_short_channel_ids_end(_their_node_id_conv, _msg_hu_conv);
				GC.KeepAlive(arg);
			long result = ret.clone_ptr();
			return result;
		}
		public long handle_query_channel_range(long _their_node_id, long _msg) {
			byte[] _their_node_id_conv = InternalUtils.decodeUint8Array(_their_node_id);
			org.ldk.structs.QueryChannelRange _msg_hu_conv = null; if (_msg < 0 || _msg > 4096) { _msg_hu_conv = new org.ldk.structs.QueryChannelRange(null, _msg); }
			if (_msg_hu_conv != null) { _msg_hu_conv.ptrs_to.AddLast(this); };
			Result_NoneLightningErrorZ ret = arg.handle_query_channel_range(_their_node_id_conv, _msg_hu_conv);
				GC.KeepAlive(arg);
			long result = ret.clone_ptr();
			return result;
		}
		public long handle_query_short_channel_ids(long _their_node_id, long _msg) {
			byte[] _their_node_id_conv = InternalUtils.decodeUint8Array(_their_node_id);
			org.ldk.structs.QueryShortChannelIds _msg_hu_conv = null; if (_msg < 0 || _msg > 4096) { _msg_hu_conv = new org.ldk.structs.QueryShortChannelIds(null, _msg); }
			if (_msg_hu_conv != null) { _msg_hu_conv.ptrs_to.AddLast(this); };
			Result_NoneLightningErrorZ ret = arg.handle_query_short_channel_ids(_their_node_id_conv, _msg_hu_conv);
				GC.KeepAlive(arg);
			long result = ret.clone_ptr();
			return result;
		}
		public bool processing_queue_high() {
			bool ret = arg.processing_queue_high();
				GC.KeepAlive(arg);
			return ret;
		}
	}

	/** Creates a new instance of RoutingMessageHandler from a given implementation */
	public static RoutingMessageHandler new_impl(RoutingMessageHandlerInterface arg, BaseMessageHandlerInterface baseMessageHandler_impl) {
		LDKRoutingMessageHandlerHolder impl_holder = new LDKRoutingMessageHandlerHolder();
		LDKRoutingMessageHandlerImpl impl = new LDKRoutingMessageHandlerImpl(arg, impl_holder);
		BaseMessageHandler baseMessageHandler = BaseMessageHandler.new_impl(baseMessageHandler_impl);
		long[] ptr_idx = bindings.LDKRoutingMessageHandler_new(impl, baseMessageHandler.instance_idx);

		impl_holder.held = new RoutingMessageHandler(null, ptr_idx[0]);
		impl_holder.held.instance_idx = ptr_idx[1];
		impl_holder.held.bindings_instance = impl;
		impl_holder.held.ptrs_to.AddLast(baseMessageHandler);
		return impl_holder.held;
	}

	/**
	 * Handle an incoming `node_announcement` message, returning `true` if it should be forwarded on,
	 * `false` or returning an `Err` otherwise.
	 * 
	 * If `their_node_id` is `None`, the message was generated by our own local node.
	 * 
	 * Note that their_node_id (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	public org.ldk.structs.Result_boolLightningErrorZ handle_node_announcement(byte[] their_node_id, org.ldk.structs.NodeAnnouncement msg) {
		long ret = bindings.RoutingMessageHandler_handle_node_announcement(this.ptr, InternalUtils.encodeUint8Array(InternalUtils.check_arr_len(their_node_id, 33)), msg.ptr);
		GC.KeepAlive(this);
		GC.KeepAlive(their_node_id);
		GC.KeepAlive(msg);
		if (ret >= 0 && ret <= 4096) { return null; }
		Result_boolLightningErrorZ ret_hu_conv = Result_boolLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Handle a `channel_announcement` message, returning `true` if it should be forwarded on, `false`
	 * or returning an `Err` otherwise.
	 * 
	 * If `their_node_id` is `None`, the message was generated by our own local node.
	 * 
	 * Note that their_node_id (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	public org.ldk.structs.Result_boolLightningErrorZ handle_channel_announcement(byte[] their_node_id, org.ldk.structs.ChannelAnnouncement msg) {
		long ret = bindings.RoutingMessageHandler_handle_channel_announcement(this.ptr, InternalUtils.encodeUint8Array(InternalUtils.check_arr_len(their_node_id, 33)), msg.ptr);
		GC.KeepAlive(this);
		GC.KeepAlive(their_node_id);
		GC.KeepAlive(msg);
		if (ret >= 0 && ret <= 4096) { return null; }
		Result_boolLightningErrorZ ret_hu_conv = Result_boolLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Handle an incoming `channel_update` message, returning true if it should be forwarded on,
	 * `false` or returning an `Err` otherwise.
	 * 
	 * If `their_node_id` is `None`, the message was generated by our own local node.
	 * 
	 * Note that their_node_id (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	public org.ldk.structs.Result_boolLightningErrorZ handle_channel_update(byte[] their_node_id, org.ldk.structs.ChannelUpdate msg) {
		long ret = bindings.RoutingMessageHandler_handle_channel_update(this.ptr, InternalUtils.encodeUint8Array(InternalUtils.check_arr_len(their_node_id, 33)), msg.ptr);
		GC.KeepAlive(this);
		GC.KeepAlive(their_node_id);
		GC.KeepAlive(msg);
		if (ret >= 0 && ret <= 4096) { return null; }
		Result_boolLightningErrorZ ret_hu_conv = Result_boolLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Gets channel announcements and updates required to dump our routing table to a remote node,
	 * starting at the `short_channel_id` indicated by `starting_point` and including announcements
	 * for a single channel.
	 */
	public org.ldk.structs.Option_C3Tuple_ChannelAnnouncementChannelUpdateChannelUpdateZZ get_next_channel_announcement(long starting_point) {
		long ret = bindings.RoutingMessageHandler_get_next_channel_announcement(this.ptr, starting_point);
		GC.KeepAlive(this);
		GC.KeepAlive(starting_point);
		if (ret >= 0 && ret <= 4096) { return null; }
		org.ldk.structs.Option_C3Tuple_ChannelAnnouncementChannelUpdateChannelUpdateZZ ret_hu_conv = org.ldk.structs.Option_C3Tuple_ChannelAnnouncementChannelUpdateChannelUpdateZZ.constr_from_ptr(ret);
		if (ret_hu_conv != null) { ret_hu_conv.ptrs_to.AddLast(this); };
		return ret_hu_conv;
	}

	/**
	 * Gets a node announcement required to dump our routing table to a remote node, starting at
	 * the node *after* the provided pubkey and including up to one announcement immediately
	 * higher (as defined by `<PublicKey as Ord>::cmp`) than `starting_point`.
	 * If `None` is provided for `starting_point`, we start at the first node.
	 * 
	 * Note that starting_point (or a relevant inner pointer) may be NULL or all-0s to represent None
	 * Note that the return value (or a relevant inner pointer) may be NULL or all-0s to represent None
	 */
	public org.ldk.structs.NodeAnnouncement get_next_node_announcement(org.ldk.structs.NodeId starting_point) {
		long ret = bindings.RoutingMessageHandler_get_next_node_announcement(this.ptr, starting_point == null ? 0 : starting_point.ptr);
		GC.KeepAlive(this);
		GC.KeepAlive(starting_point);
		if (ret >= 0 && ret <= 4096) { return null; }
		org.ldk.structs.NodeAnnouncement ret_hu_conv = null; if (ret < 0 || ret > 4096) { ret_hu_conv = new org.ldk.structs.NodeAnnouncement(null, ret); }
		if (ret_hu_conv != null) { ret_hu_conv.ptrs_to.AddLast(this); };
		return ret_hu_conv;
	}

	/**
	 * Handles the reply of a query we initiated to learn about channels
	 * for a given range of blocks. We can expect to receive one or more
	 * replies to a single query.
	 */
	public org.ldk.structs.Result_NoneLightningErrorZ handle_reply_channel_range(byte[] their_node_id, org.ldk.structs.ReplyChannelRange msg) {
		long ret = bindings.RoutingMessageHandler_handle_reply_channel_range(this.ptr, InternalUtils.encodeUint8Array(InternalUtils.check_arr_len(their_node_id, 33)), msg.ptr);
		GC.KeepAlive(this);
		GC.KeepAlive(their_node_id);
		GC.KeepAlive(msg);
		if (ret >= 0 && ret <= 4096) { return null; }
		Result_NoneLightningErrorZ ret_hu_conv = Result_NoneLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Handles the reply of a query we initiated asking for routing gossip
	 * messages for a list of channels. We should receive this message when
	 * a node has completed its best effort to send us the pertaining routing
	 * gossip messages.
	 */
	public org.ldk.structs.Result_NoneLightningErrorZ handle_reply_short_channel_ids_end(byte[] their_node_id, org.ldk.structs.ReplyShortChannelIdsEnd msg) {
		long ret = bindings.RoutingMessageHandler_handle_reply_short_channel_ids_end(this.ptr, InternalUtils.encodeUint8Array(InternalUtils.check_arr_len(their_node_id, 33)), msg.ptr);
		GC.KeepAlive(this);
		GC.KeepAlive(their_node_id);
		GC.KeepAlive(msg);
		if (ret >= 0 && ret <= 4096) { return null; }
		Result_NoneLightningErrorZ ret_hu_conv = Result_NoneLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Handles when a peer asks us to send a list of `short_channel_id`s
	 * for the requested range of blocks.
	 */
	public org.ldk.structs.Result_NoneLightningErrorZ handle_query_channel_range(byte[] their_node_id, org.ldk.structs.QueryChannelRange msg) {
		long ret = bindings.RoutingMessageHandler_handle_query_channel_range(this.ptr, InternalUtils.encodeUint8Array(InternalUtils.check_arr_len(their_node_id, 33)), msg.ptr);
		GC.KeepAlive(this);
		GC.KeepAlive(their_node_id);
		GC.KeepAlive(msg);
		if (ret >= 0 && ret <= 4096) { return null; }
		Result_NoneLightningErrorZ ret_hu_conv = Result_NoneLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Handles when a peer asks us to send routing gossip messages for a
	 * list of `short_channel_id`s.
	 */
	public org.ldk.structs.Result_NoneLightningErrorZ handle_query_short_channel_ids(byte[] their_node_id, org.ldk.structs.QueryShortChannelIds msg) {
		long ret = bindings.RoutingMessageHandler_handle_query_short_channel_ids(this.ptr, InternalUtils.encodeUint8Array(InternalUtils.check_arr_len(their_node_id, 33)), msg.ptr);
		GC.KeepAlive(this);
		GC.KeepAlive(their_node_id);
		GC.KeepAlive(msg);
		if (ret >= 0 && ret <= 4096) { return null; }
		Result_NoneLightningErrorZ ret_hu_conv = Result_NoneLightningErrorZ.constr_from_ptr(ret);
		return ret_hu_conv;
	}

	/**
	 * Indicates that there are a large number of [`ChannelAnnouncement`] (or other) messages
	 * pending some async action. While there is no guarantee of the rate of future messages, the
	 * caller should seek to reduce the rate of new gossip messages handled, especially
	 * [`ChannelAnnouncement`]s.
	 */
	public bool processing_queue_high() {
		bool ret = bindings.RoutingMessageHandler_processing_queue_high(this.ptr);
		GC.KeepAlive(this);
		return ret;
	}

}
} } }
